// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/access/AccessControl.sol";
import "./interfaces/IDataProvenance.sol";

/// @title DiffPrivacyVerifier - Verifies differential privacy ZK proofs on-chain
/// @notice Deployed on Base to verify that datasets meet epsilon-delta DP standards.
/// Integrates with DataProvenance NFT metadata for compliance attestation.
contract DiffPrivacyVerifier is AccessControl {
    bytes32 public constant VERIFIER_ADMIN_ROLE = keccak256("VERIFIER_ADMIN_ROLE");

    /// @notice Address of the UltraPlonk verifier contract (generated by Noir)
    address public noirVerifier;

    /// @notice DataProvenance contract for linking proofs to datasets
    IDataProvenance public dataProvenance;

    struct PrivacyAttestation {
        bytes32 datasetHash;
        uint256 epsilonScaled;
        uint256 deltaScaled;
        uint256 maxQueries;
        uint256 currentQueries;
        uint256 attestedAt;
        bool valid;
    }

    /// @notice tokenId => privacy attestation
    mapping(uint256 => PrivacyAttestation) public attestations;

    event PrivacyProofVerified(uint256 indexed tokenId, bytes32 datasetHash, uint256 epsilon, uint256 delta);
    event PrivacyBudgetUpdated(uint256 indexed tokenId, uint256 currentQueries, uint256 maxQueries);
    event AttestationRevoked(uint256 indexed tokenId);

    constructor(address _dataProvenance) {
        require(_dataProvenance != address(0), "DiffPrivacyVerifier: zero address");
        dataProvenance = IDataProvenance(_dataProvenance);
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(VERIFIER_ADMIN_ROLE, msg.sender);
    }

    /// @notice Verify a differential privacy proof and create an attestation for a dataset
    /// @param tokenId The DataProvenance NFT token ID
    /// @param proof The ZK proof bytes (from Noir prover)
    /// @param datasetHash The public input: hash of the dataset commitment
    /// @param epsilonScaled Epsilon parameter (scaled by 1e6)
    /// @param deltaScaled Delta parameter (scaled by 1e12)
    /// @param maxQueries Maximum queries allowed under this privacy budget
    function verifyAndAttest(
        uint256 tokenId,
        bytes calldata proof,
        bytes32 datasetHash,
        uint256 epsilonScaled,
        uint256 deltaScaled,
        uint256 maxQueries
    ) external onlyRole(VERIFIER_ADMIN_ROLE) {
        require(epsilonScaled > 0, "DiffPrivacyVerifier: zero epsilon");
        require(deltaScaled > 0, "DiffPrivacyVerifier: zero delta");
        require(maxQueries > 0, "DiffPrivacyVerifier: zero max queries");
        require(proof.length > 0, "DiffPrivacyVerifier: empty proof");

        // TODO: Call the actual Noir UltraPlonk verifier when deployed
        // require(INoirVerifier(noirVerifier).verify(proof, publicInputs), "Invalid proof");

        attestations[tokenId] = PrivacyAttestation({
            datasetHash: datasetHash,
            epsilonScaled: epsilonScaled,
            deltaScaled: deltaScaled,
            maxQueries: maxQueries,
            currentQueries: 0,
            attestedAt: block.timestamp,
            valid: true
        });

        emit PrivacyProofVerified(tokenId, datasetHash, epsilonScaled, deltaScaled);
    }

    /// @notice Record a query against the privacy budget
    /// @dev Called when data is accessed. Reverts if budget is exceeded.
    function recordQuery(uint256 tokenId) external onlyRole(VERIFIER_ADMIN_ROLE) {
        PrivacyAttestation storage att = attestations[tokenId];
        require(att.valid, "DiffPrivacyVerifier: no valid attestation");
        require(att.currentQueries < att.maxQueries, "DiffPrivacyVerifier: privacy budget exceeded");

        att.currentQueries++;
        emit PrivacyBudgetUpdated(tokenId, att.currentQueries, att.maxQueries);
    }

    /// @notice Check if a dataset has a valid privacy attestation with remaining budget
    function isCompliant(uint256 tokenId) external view returns (bool) {
        PrivacyAttestation storage att = attestations[tokenId];
        return att.valid && att.currentQueries < att.maxQueries;
    }

    /// @notice Get remaining query budget for a dataset
    function remainingBudget(uint256 tokenId) external view returns (uint256) {
        PrivacyAttestation storage att = attestations[tokenId];
        if (!att.valid || att.currentQueries >= att.maxQueries) return 0;
        return att.maxQueries - att.currentQueries;
    }

    /// @notice Revoke a privacy attestation (admin only)
    function revokeAttestation(uint256 tokenId) external onlyRole(VERIFIER_ADMIN_ROLE) {
        require(attestations[tokenId].valid, "DiffPrivacyVerifier: not valid");
        attestations[tokenId].valid = false;
        emit AttestationRevoked(tokenId);
    }

    /// @notice Update the Noir verifier contract address
    function setNoirVerifier(address _verifier) external onlyRole(DEFAULT_ADMIN_ROLE) {
        noirVerifier = _verifier;
    }
}
